/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EYAHOOGAMESADTRACK_AUTODEFS_H
#define S3EYAHOOGAMESADTRACK_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_YAHOOGAMESADTRACK_NAME "s3eYahooGamesAdTrack"
#define S3E_EXT_YAHOOGAMESADTRACK_HASH 0x24957097

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("s3eYahooGamesAdTrack", 4)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !S3EYAHOOGAMESADTRACK_AUTODEFS_H */
